on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ghostpanther.azurecr.io
        username: ${{ secrets.acr_ghostpanther_username }}
        password: ${{ secrets.acr_ghostpanther_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ghostpanther.azurecr.io/gebakscluster22:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push ghostpanther.azurecr.io/gebakscluster22:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_gebakscluster22_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep gebakscluster-22b827 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace gebakscluster-22b827`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: gebakscluster-22b827
        container-registry-url: ghostpanther.azurecr.io
        container-registry-username: ${{ secrets.acr_ghostpanther_username }}
        container-registry-password: ${{ secrets.acr_ghostpanther_password }}
        secret-name: gebaksclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: gebakscluster-22b827
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          ghostpanther.azurecr.io/gebakscluster22:${{ github.sha }}
        imagepullsecrets: |
          gebaksclustedockerauth
