on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: snacksrepo.azurecr.io
        username: ${{ secrets.acr_snacksrepo_username }}
        password: ${{ secrets.acr_snacksrepo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AppModelv2-WebApp-OpenIDConnect-DotNet" -f  "AppModelv2-WebApp-OpenIDConnect-DotNet/Dockerfile" -t snacksrepo.azurecr.io/sncakstestgeb:${{ github.sha }} --label dockerfile-path=AppModelv2-WebApp-OpenIDConnect-DotNet/Dockerfile
        docker push snacksrepo.azurecr.io/sncakstestgeb:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sncakstestgeb_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sncakstest-geb974e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sncakstest-geb974e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sncakstest-geb974e
        container-registry-url: snacksrepo.azurecr.io
        container-registry-username: ${{ secrets.acr_snacksrepo_username }}
        container-registry-password: ${{ secrets.acr_snacksrepo_password }}
        secret-name: sncakstestgedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: sncakstest-geb974e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          snacksrepo.azurecr.io/sncakstestgeb:${{ github.sha }}
        imagepullsecrets: |
          sncakstestgedockerauth
